### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by jordanbancino** [jordanbancino/SwerveIO#15]
**Describe the solution you'd like**
With the 2020 season coming to a start, we need to be prepared for the possibility of autonomous. It would be nice if we could add API functions for things like `rotate(double speed, double degrees)`, as well as things like `forward(double speed, double distance)`.

Additionally, waypoints would be a great feature to include in this, so we can generate paths and then apply them.

**Comment by jordanbancino** [comment]
Regarding that second point there, [Pathfinder](https://github.com/GrappleRobotics/Pathfinder) would be a good start. We could either add that as a dependency, or implement something similar on our own. Both would probably be equally difficult.

**Comment by jordanbancino** [comment]
WPILib has a `SwerveDriveKinematics` class that can convert trajectory path point vectors into individual module references.

**Comment by jordanbancino** [comment]
additionally, a `lock()` function should be provided in the `SwerveDrive` that, when activated, turns on the PID loop for the drive motors as well, preventing them from being moved.

**Comment by kraj011** [comment]
Have you gotten a chance to work on this? I think that being able to move for x amount of rotations in a given direction would be awesome!

**Comment by kraj011** [comment]
I also think being able to rotate to a certain theta using some sort of PID loop would be a great feature to have too

**Comment by jordanbancino** [comment]
@kraj011 We have just started working on it this week. You'll see that we do have a `drive()` function in `SwerveDrive` that takes a WPILib `ChassisSpeeds` object:

[SwerveDrive.java:167](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/SwerveDrive.java#L167)

This will be the way we do autonomous. So if you look at the documentation for `ChassisSpeeds` (in the WPILib `kinematics` package) you'll see how to create these objects. You'll basically tell the swerve drive to do things like "rotate 90 per second" or similar things. 

I definitely think it's a great idea to do something like you've proposed; if we can keep track of the angle, a PID loop would be an excellent way to rotate the angle. I was actually just talking to some team members about this earlier today, about using a PID loop to drive the chassis. We will probably require a gyro for the angular motion, since it'll give us actual feedback, instead of having to rely on vector calculations. As for linear motion, we're still working on that.

**Comment by kraj011** [comment]
Gotcha. So for Chassis Speed, when you tell it for example like you said to rotate 90 per second, is that just setting speed or are you / can you send a position to go to and it'll go there (if that makes sense lol)?

**Comment by jordanbancino** [comment]
Yes, exactly. You're setting a speed. Positioning is something very important to us that we will work on and hopefully have soon.

**Comment by kraj011** [comment]
I saw you added some fun path weaver stuff! Have you gotten a chance to test it and see if it works?

**Comment by jordanbancino** [comment]
Yep! I started testing it yesterday but our base was malfunctioning, I don't know if it was just us or a problem with the command. I'll test more tomorrow.

**Comment by kraj011** [comment]
https://github.com/Team6090/SwerveIO/blob/7652a2d7185e908baeeae06a5e1278691df413c3/src/main/java/net/bancino/robotics/swerveio/command/PathweaverSwerveDrive.java#L47

Maybe add addRequirements(swerve) here?

**Comment by jordanbancino** [comment]
Ohhhhhh, I bet you're right. I bet that is exactly why it's jerking back and forth: it's running both commands at the same time. So yeah, that would totally solve it if that's the problem. Thank you so much, I'll add that right away.

**Comment by jordanbancino** [comment]
commit 66eab776b36127bd04301f49e0659d017a320378 (HEAD -> master, origin/master, origin/HEAD)
Author: Jordan Bancino <jordan@bancino.net>
Date:   Mon Feb 17 16:27:11 2020 -0500

    Add addRequirements() call to PathweaverSwerveDrive

**Comment by kraj011** [comment]
Awesome! Hopefully that solves it! Ill probably be able to test tomorrow! Ill keep you posted!

**Comment by jordanbancino** [comment]
Yeah hopefully! I'll test tomorrow as well. Thank you!

**Comment by kraj011** [comment]
Hey hey! So i went ahead and generated a trajectory last night to test the autonomous feature, however when I run it i don’t think its actually doing anything. It just kinda runs at full speed for a while. Anything i can do to test?

**Comment by kraj011** [comment]
When i generate my pathweaver trajectory, what unit should i run it in? I have it set to inches currently. Is that correct?

**Comment by jordanbancino** [comment]
Oh, darn, that's quite sad. I figured it probably wouldn't work first go. You can take a look at the [`PathweaverSwerveDrive`](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/command/PathweaverSwerveDrive.java) command and see if there's an error there. Though, that's pretty simple. The complex stuff really happens in [`SwerveIOUtils`](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/SwerveIOUtils.java), namely in [`convertToChassisSpeeds`](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/SwerveIOUtils.java#L179) and [`getAngularVelocity`](https://github.com/Team6090/SwerveIO/blob/master/src/main/java/net/bancino/robotics/swerveio/SwerveIOUtils.java#L195). See if you can find an error with my logic, math, or assumptions. I'll hopefully get to test this more tonight and see if I can help figure it out.

---

Units really shouldn't matter... oh, wait, I bet they do. Try doing it in meters, because all of our calculations assume meters.

**Comment by jordanbancino** [comment]
We started our testing, and with a little bit of tuning, we do have a working autonomous. it isn't super reliable yet but we still have a lot of tuning of our robot parameters so I'm not worried about that, I think itll work well.

**Comment by jordanbancino** [comment]
SwerveIO is pretty much fully compatible with PathWeaver's trajectories, so I am closing this. If there are any problems with `PathweaverSwerveDrive`, just open new issues on it.
