### ISSUE TITLE
Virtual Swerve Module

### ISSUE THREAD

**Issue by jordanbancino** [jordanbancino/SwerveIO#9]
I think it would be really beneficial to have something like a `VirtualSwerveModule` that doesn't actually use any hardware, but still has simulated motors and encoders that can receive input and generate output. This can be useful for debugging, possibly.

~~Furthermore, I would also like to somehow create a `GenericSwerveModule` that takes two motor controllers (could be of differing types, we just need them to implement WPILib's `SpeedController`) and a pivot encoder. The only tricky part is knowing what form the encoder takes, because every encoder implementation is different. For instance, it could be an `Encoder`, or an `AnalogInput` or even a REVRobotics' `CANEncoder`, and every one of these operates fundamentally different. Perhaps we should write a generic encoder interface that can be implemented.~~ **This has all been added**

**Comment by jordanbancino** [comment]
The `Encoder` interface in `net.bancino.robotics.swerveio.encoder` provides the solution to the problem we face with the difference in encoder implementations.

**Comment by kraj011** [comment]
@jordanbancino I wouldn't mind making some super basic Motor Controller object that has some methods for setting its speed or what not. What sort of things exactly are you looking to implement with the VirtualSwerveModule class? Just a copy, for example, of the MK2SwerveModule Class but instead of actual hardware objects we use our own custom "virtual" objects? If so, I would be more than happy to take this on!

**Comment by jordanbancino** [comment]
@kraj011 Alright, yeah, that would be great! Basically what you've described is good, I was thinking it could all be done in the `VirtualSwerveModule` class, but if you need other objects, I guess just make a `virtual` package under `module`. I'd like it to behave just like a real module, complete with encoder feedback and PID controls, so I have a feeling it's going to be a lot more complex than it seems, because I don't want it to just be a black whole, I'd like it to actually respond to the inputs it's given. So we'll probably need to run a thread that updates the encoder position based on the given speed. Almost like a reverse PID, it converts speed into position instead of traditionally converting position into a speed. So you could probably use the `MiniPID` class to do it if you want. But honestly I'm not entirely sure what I want it to look like, so I guess just try something and we can figure it out once you've got some code.

**Comment by jordanbancino** [comment]
Oooh, we'll also want to have options to set the encoder intervals, effectively controlling how many counts it takes to do a revolution.

**Comment by kraj011** [comment]
Sweet! I'll start off with some basic virtual implementations of some of the objects we would need and from there we can figure out how to make them respond properly to inputs etc etc

**Comment by jordanbancino** [comment]
Alright, that sounds good!

**Comment by kraj011** [comment]
@jordanbancino I started to write some virtual implementations, but now that I am writing it I have a question. Would you rather create virtual motor / speed control objects that extend ```SpeedController``` and have the user create a ```GenericSwerveModule``` object and pass in the virtual motor controllers? Or would you rather create a whole new implementation of a swerve module that provides functionality that the ```GenericSwerveModule``` does not provide?

**Comment by jordanbancino** [comment]
Good question. I'd say either would work. My initial thought was to create a whole new implementation of a swerve module. So I'd say let's do that, let's create a virtual swerve module, instead of virtual motor controllers.

**Comment by kraj011** [comment]
Perfect :D Should the virtual swerve module extend the Generic swerve module or should we make this one from scratch?

**Comment by jordanbancino** [comment]
Making it from scratch would be easier, you have more control and freedom that way.

**Comment by jordanbancino** [comment]
#10

**Comment by jordanbancino** [comment]
See #10
